package com.example.testapp.students;

/* Generated by SpringFlow. DO NOT EDIT. */

import java.util.List;
import java.util.Optional;

/**
 * Repository interface for Student.
 *
 * Extend Spring Data JPA:
 *   public interface StudentRepository
 *       extends org.springframework.data.jpa.repository.JpaRepository<Student, Long> {}
 */
public interface StudentRepository {

    List<Student> findAll();

    Optional<Student> findById(Long id);

    Student save(Student entity);

    void deleteById(Long id);

    long count();
}
