package com.example.testapp.students;

/* Generated by SpringFlow. DO NOT EDIT. */

import dev.springflow.core.annotation.Endpoint;
import dev.springflow.core.annotation.EndpointMethod;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

@Endpoint
public class StudentEndpoint {

    private final List<Student> students = new ArrayList<>();

    private final AtomicLong idGenerator = new AtomicLong(1);

    @EndpointMethod
    public List<Student> findAll() {
        return new ArrayList<>(students);
    }

    @EndpointMethod
    public Student findById(Long id) {
        return students.stream()
                .filter(item -> item.getId().equals(id))
                .findFirst()
                .orElse(null);
    }

    @EndpointMethod
    public Student create(
            String firstName,
            String lastName,
            String email,
            Double gpa
    ) {
        Student item = new Student(
                idGenerator.getAndIncrement(),
                firstName,
                lastName,
                email,
                gpa,
                true
        );


        students.add(item);
        return item;
    }

    @EndpointMethod
    public Student update(
            Long id,
            String firstName,
            String lastName,
            String email,
            Double gpa,
            boolean active
    ) {
        Student item = findById(id);

        if (item == null) {
            return null;
        }

        item.setFirstName(firstName);
        item.setLastName(lastName);
        item.setEmail(email);
        item.setGpa(gpa);
        item.setActive(active);

        return item;
    }

    @EndpointMethod
    public boolean delete(Long id) {
        return students.removeIf(
                item -> item.getId().equals(id)
        );
    }
}
