package com.example.testapp.students;

/* Generated by SpringFlow. DO NOT EDIT. */

import org.springframework.stereotype.Component;

@Component
public class StudentMapper {

    public StudentDto toDto(Student entity) {

        StudentDto dto = new StudentDto();

        dto.setFirstName(entity.getFirstName());
        dto.setLastName(entity.getLastName());
        dto.setEmail(entity.getEmail());
        dto.setGpa(entity.getGpa());
        dto.setActive(entity.getActive());

        return dto;
    }

    public Student toEntity(StudentDto dto) {

        Student entity = new Student();

        entity.setFirstName(dto.getFirstName());
        entity.setLastName(dto.getLastName());
        entity.setEmail(dto.getEmail());
        entity.setGpa(dto.getGpa());
        entity.setActive(dto.getActive());

        return entity;
    }
}
