package com.example.testapp.students;

/* Generated by SpringFlow. DO NOT EDIT. */

import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class StudentService {

    private final List<Student> store = new ArrayList<>();
    private long nextId = 1;

    public List<Student> findAll() {
        return new ArrayList<>(store);
    }

    public Optional<Student> findById(Long id) {
        return store.stream()
                .filter(item -> item.getId().equals(id))
                .findFirst();
    }

    public Student save(Student item) {
        item.setId(nextId++);
        store.add(item);
        return item;
    }

    public boolean delete(Long id) {
        return store.removeIf(
                item -> item.getId().equals(id)
        );
    }
}
