package dev.springflow.typescript;

public final class TypeScriptGenerator {

    private TypeScriptGenerator() {
    }

    public static String generate(EndpointMetadata endpoint) {

        StringBuilder output = new StringBuilder();

        output.append("""
                /**
                 * Generated by SpringFlow.
                 * DO NOT EDIT.
                 */

                """);

        output.append("export const ")
                .append(endpoint.className())
                .append(" = {\n");

        for (MethodMetadata method : endpoint.methods()) {

            output.append("  ")
                    .append(method.name())
                    .append(": async (): Promise<")
                    .append(mapType(method.returnType()))
                    .append("> => {\n");

            output.append("    const response = await fetch('/springflow/")
                    .append(endpoint.className())
                    .append("/")
                    .append(method.name())
                    .append("');\n");

            output.append("    return await response.json();\n");
            output.append("  },\n");
        }

        output.append("};\n");

        return output.toString();
    }

    private static String mapType(String javaType) {

        return switch (javaType) {
            case "void" -> "void";
            case "int", "long", "double", "float",
                 "Integer", "Long", "Double", "Float" -> "number";
            case "boolean", "Boolean" -> "boolean";
            case "String" -> "string";
            default -> javaType;
        };
    }
}
