package dev.springflow.processor.generator;

public class SpringFlowClientGenerator {

    public String generate() {

        return """
                /* Generated by SpringFlow. DO NOT EDIT. */

                export class SpringFlowClient {

                    static async get<T>(
                        url: string,
                        params?: Record<string, unknown>
                    ): Promise<T> {

                        const searchParams =
                            new URLSearchParams();

                        if (params) {
                            for (const [key, value] of Object.entries(params)) {
                                searchParams.set(
                                    key,
                                    String(value)
                                );
                            }
                        }

                        const query =
                            searchParams.toString();

                        const finalUrl =
                            url +
                            (query ? `?${query}` : "");

                        const response =
                            await fetch(finalUrl);

                        if (!response.ok) {

                            throw new Error(
                                `SpringFlow request failed: ${response.status} ${response.statusText}`
                            );
                        }

                        return await response.json();
                    }

                    static async post<T>(
                        url: string,
                        body?: Record<string, unknown>
                    ): Promise<T> {

                        const response =
                            await fetch(url, {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json',
                                },
                                body: body
                                    ? JSON.stringify(body)
                                    : undefined,
                            });

                        if (!response.ok) {

                            throw new Error(
                                `SpringFlow request failed: ${response.status} ${response.statusText}`
                            );
                        }

                        return await response.json();
                    }
                }
                """;
    }
}