package dev.springflow.processor.generator;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.lang.model.element.Element;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;

import dev.springflow.core.annotation.EndpointMethod;

public class TypeScriptGenerator {

    private final Types types;
    private final Elements elements;

    public TypeScriptGenerator(
            Types types,
            Elements elements) {

        this.types = types;
        this.elements = elements;
    }

    /**
     * Generate a TypeScript API class for a Java endpoint.
     */
    public String generate(TypeElement endpoint) {

        StringBuilder output =
                new StringBuilder();

        String className =
                endpoint.getSimpleName().toString();

        output.append(
                "/* Generated by SpringFlow. DO NOT EDIT. */\n\n"
        );

        /*
         * SpringFlowClient import.
         */
        output.append(
                "import { SpringFlowClient } from \""
        )
                .append(buildClientImport(endpoint))
                .append("\";\n");

        /*
         * Collect all custom model types used by
         * endpoint methods.
         */
        Set<TypeElement> models =
                new LinkedHashSet<>();

        for (Element element :
                endpoint.getEnclosedElements()) {

            if (!(element instanceof ExecutableElement method)) {
                continue;
            }

            if (method.getAnnotation(
                    EndpointMethod.class) == null) {
                continue;
            }

            collectModels(
                    method.getReturnType(),
                    models
            );

            for (VariableElement parameter :
                    method.getParameters()) {

                collectModels(
                        parameter.asType(),
                        models
                );
            }
        }

        /*
         * Generate imports for models.
         */
        for (TypeElement model : models) {

            if (model.equals(endpoint)) {
                continue;
            }

            String modelName =
                    model.getSimpleName().toString();

            String modelPackage =
                    elements.getPackageOf(model)
                            .getQualifiedName()
                            .toString();

            String endpointPackage =
                    elements.getPackageOf(endpoint)
                            .getQualifiedName()
                            .toString();

            String relativePath =
                    relativeImport(
                            endpointPackage,
                            modelPackage,
                            modelName
                    );

            output.append(
                    "import type { "
            )
                    .append(modelName)
                    .append(" } from \"")
                    .append(relativePath)
                    .append("\";\n");
        }

        output.append("\n");

        output.append("export class ")
                .append(className)
                .append(" {\n\n");

        /*
         * Generate endpoint methods.
         */
        for (Element element :
                endpoint.getEnclosedElements()) {

            if (!(element instanceof ExecutableElement method)) {
                continue;
            }

            if (method.getAnnotation(
                    EndpointMethod.class) == null) {
                continue;
            }

            generateMethod(
                    output,
                    endpoint,
                    method
            );
        }

        output.append("}\n");

        return output.toString();
    }

    /**
     * Generate a TypeScript interface for a Java model.
     */
    public String generateModel(TypeElement model) {

        StringBuilder output =
                new StringBuilder();

        String className =
                model.getSimpleName().toString();

        String packageName =
                elements.getPackageOf(model)
                        .getQualifiedName()
                        .toString();

        /*
         * Find custom model types referenced by fields.
         */
        Set<TypeElement> referencedModels =
                new LinkedHashSet<>();

        for (Element element :
                model.getEnclosedElements()) {

            if (!(element instanceof VariableElement field)) {
                continue;
            }

            if (field.getModifiers()
                    .contains(Modifier.STATIC)) {
                continue;
            }

            collectModels(
                    field.asType(),
                    referencedModels
            );
        }

        /*
         * Never import the model itself.
         */
        referencedModels.remove(model);

        output.append(
                "/* Generated by SpringFlow. DO NOT EDIT. */\n\n"
        );

        /*
         * Generate model imports.
         */
        for (TypeElement referencedModel :
                referencedModels) {

            String referencedName =
                    referencedModel
                            .getSimpleName()
                            .toString();

            String referencedPackage =
                    elements.getPackageOf(
                            referencedModel
                    )
                            .getQualifiedName()
                            .toString();

            String relativePath =
                    relativeImport(
                            packageName,
                            referencedPackage,
                            referencedName
                    );

            output.append(
                    "import type { "
            )
                    .append(referencedName)
                    .append(" } from \"")
                    .append(relativePath)
                    .append("\";\n");
        }

        if (!referencedModels.isEmpty()) {
            output.append("\n");
        }

        output.append(
                "export interface "
        )
                .append(className)
                .append(" {\n");

        /*
         * Generate fields.
         */
        for (Element element :
                model.getEnclosedElements()) {

            if (!(element instanceof VariableElement field)) {
                continue;
            }

            /*
             * Ignore static fields.
             */
            if (field.getModifiers()
                    .contains(Modifier.STATIC)) {
                continue;
            }

            /*
             * Ignore compiler-generated fields.
             */
            if (field.getModifiers()
                    .contains(Modifier.PRIVATE)
                    && field.getSimpleName()
                    .toString()
                    .startsWith("$")) {
                continue;
            }

            output.append("    ")
                    .append(
                            field.getSimpleName()
                    )
                    .append(": ")
                    .append(
                            toTypeScript(
                                    field.asType()
                            )
                    )
                    .append(";\n");
        }

        output.append("}\n");

        return output.toString();
    }

    /**
     * Discover custom Java model types recursively.
     */
    private void collectModels(
            TypeMirror type,
            Set<TypeElement> models) {

        if (type == null) {
            return;
        }

        /*
         * Primitive / void.
         */
        if (type.getKind().isPrimitive()
                || type.getKind() == TypeKind.VOID) {
            return;
        }

        /*
         * Arrays.
         */
        if (type.getKind() == TypeKind.ARRAY) {

            ArrayType array =
                    (ArrayType) type;

            collectModels(
                    array.getComponentType(),
                    models
            );

            return;
        }

        /*
         * Declared types.
         */
        if (type instanceof DeclaredType declaredType) {

            Element element =
                    declaredType.asElement();

            if (!(element instanceof TypeElement typeElement)) {
                return;
            }

            String qualifiedName =
                    typeElement
                            .getQualifiedName()
                            .toString();

            /*
             * Java standard classes are not SpringFlow models.
             */
            if (!isJavaType(qualifiedName)) {

                models.add(typeElement);
            }

            /*
             * Recursively inspect generic arguments.
             */
            for (TypeMirror argument :
                    declaredType.getTypeArguments()) {

                collectModels(
                        argument,
                        models
                );
            }
        }
    }

    /**
     * Determine whether a type belongs to Java/Jakarta
     * standard libraries.
     */
    private boolean isJavaType(
            String qualifiedName) {

        return qualifiedName.startsWith("java.")
                || qualifiedName.startsWith("javax.")
                || qualifiedName.startsWith("jakarta.");
    }

    /**
     * Generate endpoint method.
     */
   /**
 * Generate one TypeScript method.
 */
private void generateMethod(
        StringBuilder output,
        TypeElement endpoint,
        ExecutableElement method) {

    String methodName =
            method.getSimpleName().toString();

    String returnType =
            toTypeScript(
                    method.getReturnType()
            );

    List<? extends VariableElement> parameters =
            method.getParameters();

    /*
     * Method signature
     */
    output.append("    static async ")
            .append(methodName)
            .append("(");

    for (int i = 0; i < parameters.size(); i++) {

        VariableElement parameter =
                parameters.get(i);

        if (i > 0) {
            output.append(", ");
        }

        output.append(
                parameter.getSimpleName()
        );

        output.append(": ");

        output.append(
                toTypeScript(
                        parameter.asType()
                )
        );
    }

    output.append("): Promise<")
            .append(returnType)
            .append("> {\n");

    /*
     * No parameters
     */
    if (parameters.isEmpty()) {

        output.append(
                "        return SpringFlowClient.get<"
        )
                .append(returnType)
                .append(">(\n");

        output.append("            \"")
                .append(
                        buildUrl(
                                endpoint,
                                method
                        )
                )
                .append("\"\n");

        output.append(
                "        );\n"
        );

    } else {

        /*
         * Parameters exist — use POST with JSON body.
         */
        output.append(
                "        return SpringFlowClient.post<"
        )
                .append(returnType)
                .append(">(\n");

        output.append("            \"")
                .append(
                        buildUrl(
                                endpoint,
                                method
                        )
                )
                .append("\",\n");

        output.append(
                "            {\n"
        );

        for (VariableElement parameter :
                parameters) {

            String name =
                    parameter
                            .getSimpleName()
                            .toString();

            output.append(
                    "                "
            )
                    .append(name)
                    .append(": ")
                    .append(name)
                    .append(",\n");
        }

        output.append(
                "            }\n"
        );

        output.append(
                "        );\n"
        );
    }

    output.append(
            "    }\n\n"
    );
}

    /**
     * Build SpringFlow endpoint URL.
     */
    private String buildUrl(
            TypeElement endpoint,
            ExecutableElement method) {

        return "/springflow/"
                + endpoint.getSimpleName()
                + "/"
                + method.getSimpleName();
    }

    /**
     * Convert Java type to TypeScript type.
     */
    private String toTypeScript(
            TypeMirror type) {

        if (type == null) {
            return "unknown";
        }

        /*
         * void
         */
        if (type.getKind() == TypeKind.VOID) {
            return "void";
        }

        /*
         * boolean
         */
        if (type.getKind() == TypeKind.BOOLEAN) {
            return "boolean";
        }

        /*
         * numeric primitives
         */
        if (type.getKind() == TypeKind.INT
                || type.getKind() == TypeKind.LONG
                || type.getKind() == TypeKind.DOUBLE
                || type.getKind() == TypeKind.FLOAT
                || type.getKind() == TypeKind.SHORT
                || type.getKind() == TypeKind.BYTE) {

            return "number";
        }

        /*
         * char
         */
        if (type.getKind() == TypeKind.CHAR) {
            return "string";
        }

        /*
         * arrays
         */
        if (type.getKind() == TypeKind.ARRAY) {

            ArrayType array =
                    (ArrayType) type;

            return toTypeScript(
                    array.getComponentType()
            ) + "[]";
        }

        String name =
                type.toString();

        /*
         * Standard Java types.
         */
        return switch (name) {

            case "java.lang.String",
                 "java.lang.Character" ->
                    "string";

            case "java.lang.Boolean" ->
                    "boolean";

            case "java.lang.Integer",
                 "java.lang.Long",
                 "java.lang.Double",
                 "java.lang.Float",
                 "java.lang.Short",
                 "java.lang.Byte",
                 "java.math.BigDecimal",
                 "java.math.BigInteger" ->
                    "number";

            case "java.lang.Object" ->
                    "unknown";

            default -> {

                /*
                 * List<T>
                 */
                if (name.startsWith(
                        "java.util.List<")) {

                    String inner =
                            name.substring(
                                    "java.util.List<".length(),
                                    name.length() - 1
                            );

                    yield mapGenericType(
                            inner
                    ) + "[]";
                }

                /*
                 * Set<T>
                 */
                if (name.startsWith(
                        "java.util.Set<")) {

                    String inner =
                            name.substring(
                                    "java.util.Set<".length(),
                                    name.length() - 1
                            );

                    yield mapGenericType(
                            inner
                    ) + "[]";
                }

                /*
                 * Optional<T>
                 */
                if (name.startsWith(
                        "java.util.Optional<")) {

                    String inner =
                            name.substring(
                                    "java.util.Optional<".length(),
                                    name.length() - 1
                            );

                    yield mapGenericType(
                            inner
                    ) + " | null";
                }

                /*
                 * Map<K,V>
                 */
                if (name.startsWith(
                        "java.util.Map<")) {

                    String inner =
                            name.substring(
                                    "java.util.Map<".length(),
                                    name.length() - 1
                            );

                    int separator =
                            topLevelComma(inner);

                    String key =
                            mapGenericType(
                                    inner.substring(
                                            0,
                                            separator
                                    )
                            );

                    String value =
                            mapGenericType(
                                    inner.substring(
                                            separator + 1
                                    )
                            );

                    yield "Record<"
                            + key
                            + ", "
                            + value
                            + ">";
                }

                /*
                 * Custom SpringFlow model.
                 */
                yield toTypeScriptName(name);
            }
        };
    }

    /**
     * Convert a Java type expression used inside a generic
     * (e.g. a Map key or value) to TypeScript.
     */
    private String mapGenericType(
            String expression) {

        expression =
                expression.trim();

        return switch (expression) {

            case "java.lang.String",
                 "java.lang.Character" ->
                    "string";

            case "java.lang.Boolean" ->
                    "boolean";

            case "java.lang.Integer",
                 "java.lang.Long",
                 "java.lang.Double",
                 "java.lang.Float",
                 "java.lang.Short",
                 "java.lang.Byte",
                 "java.math.BigDecimal",
                 "java.math.BigInteger" ->
                    "number";

            case "java.lang.Object" ->
                    "unknown";

            default -> {

                if (expression.startsWith(
                        "java.util.List<")) {

                    String inner =
                            expression.substring(
                                    "java.util.List<".length(),
                                    expression.length() - 1
                            );

                    yield mapGenericType(inner)
                            + "[]";
                }

                if (expression.startsWith(
                        "java.util.Set<")) {

                    String inner =
                            expression.substring(
                                    "java.util.Set<".length(),
                                    expression.length() - 1
                            );

                    yield mapGenericType(inner)
                            + "[]";
                }

                if (expression.startsWith(
                        "java.util.Optional<")) {

                    String inner =
                            expression.substring(
                                    "java.util.Optional<".length(),
                                    expression.length() - 1
                            );

                    yield mapGenericType(inner)
                            + " | null";
                }

                if (expression.startsWith(
                        "java.util.Map<")) {

                    String inner =
                            expression.substring(
                                    "java.util.Map<".length(),
                                    expression.length() - 1
                            );

                    int separator =
                            topLevelComma(inner);

                    yield "Record<"
                            + mapGenericType(
                            inner.substring(
                                    0,
                                    separator
                            )
                    )
                            + ", "
                            + mapGenericType(
                            inner.substring(
                                    separator + 1
                            )
                    )
                            + ">";
                }

                yield toTypeScriptName(expression);
            }
        };
    }

    /**
     * Find the generic-argument separator comma that sits at
     * nesting depth zero.
     */
    private static int topLevelComma(
            String text) {

        int depth = 0;

        for (int i = 0;
             i < text.length();
             i++) {

            char c = text.charAt(i);

            if (c == '<') {
                depth++;
            } else if (c == '>') {
                depth--;
            } else if (c == ','
                    && depth == 0) {

                return i;
            }
        }

        throw new IllegalArgumentException(
                "No top-level comma in: "
                        + text
        );
    }

    /**
     * Convert Java qualified name to simple
     * TypeScript name.
     */
    private String toTypeScriptName(
            String javaName) {

        int genericStart =
                javaName.indexOf('<');

        if (genericStart >= 0) {

            javaName =
                    javaName.substring(
                            0,
                            genericStart
                    );
        }

        int lastDot =
                javaName.lastIndexOf('.');

        if (lastDot >= 0) {

            return javaName.substring(
                    lastDot + 1
            );
        }

        return javaName;
    }

    /**
     * Build relative import to SpringFlowClient.ts.
     *
     * Example:
     *
     * dev.springflow.demo.employees
     *
     * generated:
     *
     * springflow/generated/
     * dev/springflow/demo/employees/
     *
     * SpringFlowClient is:
     *
     * springflow/generated/SpringFlowClient.ts
     *
     * Therefore:
     *
     * ../../../../SpringFlowClient
     */
    private String buildClientImport(
            TypeElement endpoint) {

        String packageName =
                elements.getPackageOf(endpoint)
                        .getQualifiedName()
                        .toString();

        if (packageName.isBlank()) {
            return "./SpringFlowClient";
        }

        int depth =
                packageName.split("\\.").length;

        return "../".repeat(depth)
                + "SpringFlowClient";
    }

    /**
     * Build relative TypeScript import between
     * Java package generated directories.
     *
     * Example:
     *
     * endpoint:
     * dev.springflow.demo.employees
     *
     * model:
     * dev.springflow.demo.finance
     *
     * result:
     *
     * ../finance/Model
     */
    private String relativeImport(
            String fromPackage,
            String toPackage,
            String typeName) {

        String[] from =
                packageParts(fromPackage);

        String[] to =
                packageParts(toPackage);

        int common =
                0;

        while (common < from.length
                && common < to.length
                && from[common]
                .equals(to[common])) {

            common++;
        }

        StringBuilder path =
                new StringBuilder();

        /*
         * Go back from endpoint package.
         */
        for (int i = common;
             i < from.length;
             i++) {

            path.append("../");
        }

        /*
         * Go down into target package.
         */
        for (int i = common;
             i < to.length;
             i++) {

            path.append(to[i])
                    .append("/");
        }

        path.append(typeName);

        /*
         * Same package.
         */
        if (path.length() == 0) {
            return "./" + typeName;
        }

        /*
         * Relative paths must start with ./ or ../
         */
        String result =
                path.toString();

        if (!result.startsWith("../")) {
            result = "./" + result;
        }

        return result;
    }

    private String[] packageParts(
            String packageName) {

        if (packageName == null
                || packageName.isBlank()) {

            return new String[0];
        }

        return packageName.split("\\.");
    }
}