/* Generated by SpringFlow. DO NOT EDIT. */

import { useState, useEffect } from "react";
import { StudentEndpoint } from "../api";
import type { Student } from "../api";

export function useStudents() {

    const [students, setStudents] = useState<Student[]>([]);

    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const load = async () => {
        try {
            setLoading(true);
            const data = await StudentEndpoint.findAll();
            setStudents(data);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to load"
            );
        } finally {
            setLoading(false);
        }
    };

    const create = async (firstName: string, lastName: string, email: string, gpa: number): Promise<Student> => {
        const result = await StudentEndpoint.create(firstName, lastName, email, gpa);
        setStudents(prev => [...prev, result]);
        return result;
    };

    const update = async (id: number, firstName: string, lastName: string, email: string, gpa: number, active: boolean): Promise<Student> => {
        const result = await StudentEndpoint.update(id, firstName, lastName, email, gpa, active);
        setStudents(prev =>
            prev.map(item =>
                item.id === id ? result : item
            )
        );
        return result;
    };

    const remove = async (id: number) => {
        await StudentEndpoint.delete(id);
        setStudents(prev =>
            prev.filter(item => item.id !== id)
        );
    };

    useEffect(() => {
        load();
    }, []);

    return {
            students,
            loading,
            error,
            create,
            update,
            remove,
            reload: load,
    };
}
