/* Generated by SpringFlow. DO NOT EDIT. */

import { useState } from "react";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { Toast } from "../components/Toast";
import { SearchInput } from "../components/SearchInput";
import { StatusBadge } from "../components/StatusBadge";
import { useStudents } from "../hooks/useStudents";
import type { Student } from "../api";

export default function StudentPage() {

    const { students, loading, error, create, update, remove, reload } = useStudents();

    const [search, setSearch] = useState("");
    const [showForm, setShowForm] = useState(false);
    const [editing, setEditing] = useState<Student | null>(null);

    const [showDelete, setShowDelete] = useState(false);
    const [deleteTarget, setDeleteTarget] = useState<Student | null>(null);

    const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);

    const filtered = students.filter(item =>
        JSON.stringify(item)
            .toLowerCase()
            .includes(search.toLowerCase())
    );

    const showToast = (message: string, type: "success" | "error" = "success") => {
        setToast({ message, type });
        setTimeout(() => setToast(null), 3000);
    };

    const openCreate = () => {
        setEditing(null);
        setShowForm(true);
    };

    const openEdit = (item: Student) => {
        setEditing(item);
        setShowForm(true);
    };

    const handleSave = async (data: Record<string, unknown>) => {
        try {
            if (editing) {
                await update(editing.id as number, data["firstName"] as string, data["lastName"] as string, data["email"] as string, data["gpa"] as number, data["active"] as boolean);
                showToast("Student updated");
            } else {
                await create(data["firstName"] as string, data["lastName"] as string, data["email"] as string, data["gpa"] as number);
                showToast("Student created");
            }

            setShowForm(false);
            setEditing(null);
        } catch (err) {
            showToast(
                err instanceof Error ? err.message : "Operation failed",
                "error"
            );
        }
    };

    const handleDelete = async () => {
        if (!deleteTarget) return;
        try {
            await remove(deleteTarget.id as number);
            setShowDelete(false);
            setDeleteTarget(null);
            showToast("Student deleted");
        } catch (err) {
            showToast(
                err instanceof Error ? err.message : "Delete failed",
                "error"
            );
        }
    };

    if (loading) {
        return <div className="p-8 text-slate-500">Loading...</div>;
    }

    if (error) {
        return <div className="p-8 text-red-500">{error}</div>;
    }

    return (
        <div className="mx-auto max-w-5xl p-8">

            <div className="mb-6 flex items-center justify-between">
                <h1 className="text-2xl font-bold text-slate-900">Students</h1>

                <button
                    onClick={openCreate}
                    className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
                >
                    + New Student
                </button>
            </div>

            <SearchInput
                value={search}
                onChange={setSearch}
                placeholder="Search students..."
            />

            <div className="mt-4 overflow-hidden rounded-xl border bg-white shadow">
                <table className="w-full text-left text-sm">

                    <thead className="border-b bg-slate-50 text-xs font-medium uppercase text-slate-500">
                        <tr>
                            <th className="px-4 py-3">First Name</th>
                            <th className="px-4 py-3">Last Name</th>
                            <th className="px-4 py-3">Email</th>
                            <th className="px-4 py-3">Gpa</th>
                            <th className="px-4 py-3">Active</th>
                            <th className="px-4 py-3 text-right">Actions</th>
                        </tr>
                    </thead>

                    <tbody className="divide-y">
                        {filtered.length === 0 && (
                            <tr>
                                <td colSpan={6} className="px-4 py-8 text-center text-slate-400">
                                    No students found
                                </td>
                            </tr>
                        )}

                        {filtered.map(item => (
                            <tr key={item.id} className="hover:bg-slate-50">
                                <td className="px-4 py-3">{item.firstName}</td>
                                <td className="px-4 py-3">{item.lastName}</td>
                                <td className="px-4 py-3">{item.email}</td>
                                <td className="px-4 py-3">{item.gpa}</td>
                                <td className="px-4 py-3"><StatusBadge active={item.active} /></td>
                                <td className="flex justify-end gap-2 px-4 py-3">
                                    <button
                                        onClick={() => openEdit(item)}
                                        className="rounded border px-3 py-1 text-xs font-medium text-slate-600 hover:bg-slate-100"
                                    >
                                        Edit
                                    </button>

                                    <button
                                        onClick={() => {
                                            setDeleteTarget(item);
                                            setShowDelete(true);
                                        }}
                                        className="rounded border border-red-200 px-3 py-1 text-xs font-medium text-red-600 hover:bg-red-50"
                                    >
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {showForm && (
                <dialog open className="rounded-xl border bg-white p-6 shadow-xl">
                    <h2 className="mb-4 text-lg font-semibold">
                        {editing ? "Edit Student" : "New Student"
                    </h2>

                    <form
                        onSubmit={(e) => {
                            e.preventDefault();
                            const formData = new FormData(e.currentTarget);
                            const data: Record<string, unknown> = {};
                            data["firstName"] = String(formData.get("firstName"));
                            data["lastName"] = String(formData.get("lastName"));
                            data["email"] = String(formData.get("email"));
                            data["gpa"] = Number(formData.get("gpa"));

                            handleSave(data);
                        }}
                        className="space-y-4"
                    >
                        <div>
                            <label className="mb-1 block text-sm font-medium text-slate-700">First Name</label>
                            <input
                                type="text"
                                name="firstName"
                                defaultValue={editing?.firstName ?? ""}
                                maxLength={100}
                                required={true}
                                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                            />
                        </div>

                        <div>
                            <label className="mb-1 block text-sm font-medium text-slate-700">Last Name</label>
                            <input
                                type="text"
                                name="lastName"
                                defaultValue={editing?.lastName ?? ""}
                                maxLength={100}
                                required={true}
                                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                            />
                        </div>

                        <div>
                            <label className="mb-1 block text-sm font-medium text-slate-700">Email</label>
                            <input
                                type="text"
                                name="email"
                                defaultValue={editing?.email ?? ""}
                                required={true}
                                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                            />
                        </div>

                        <div>
                            <label className="mb-1 block text-sm font-medium text-slate-700">Gpa</label>
                            <input
                                type="number"
                                name="gpa"
                                defaultValue={editing?.gpa ?? ""}
                                required={false}
                                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                            />
                        </div>

                        <div className="flex justify-end gap-3 pt-2">
                            <button
                                type="button"
                                onClick={() => { setShowForm(false); setEditing(null); }}
                                className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
                            >
                                Cancel
                            </button>

                            <button
                                type="submit"
                                className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
                            >
                                {editing ? "Save" : "Create"}
                            </button>
                        </div>
                    </form>
                </dialog>
            )}

            <ConfirmDialog
                open={showDelete}
                title="Delete Student"
                message={`Are you sure you want to delete this student?`}
                confirmLabel="Delete"
                destructive
                onConfirm={handleDelete}
                onCancel={() => { setShowDelete(false); setDeleteTarget(null); }}
            />

            {toast && (
                <Toast message={toast.message} type={toast.type} />
            )}
        </div>
    );
}
