package dev.springflow.cli.generator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Manages backup of SpringFlow-generated files
 * before overwriting them.
 *
 * <p>Generated files are identified by the marker
 * comment {@code /* Generated by SpringFlow. *}.
 * Developer-created files are never overwritten.
 */
public class BackupManager {

    private static final String MARKER =
            "Generated by SpringFlow";

    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern(
                    "yyyyMMddHHmmss"
            );

    /**
     * Check if a file is SpringFlow-generated.
     */
    public static boolean isGenerated(Path path) {

        if (!Files.exists(path)) {
            return false;
        }

        try {

            String content =
                    Files.readString(path);

            return content.contains(MARKER);

        } catch (IOException e) {
            return false;
        }
    }

    /**
     * Backup a generated file by renaming it to
     * {@code filename.timestamp.old}.
     *
     * <p>If the file does not exist or is not
     * generated, this is a no-op.
     *
     * <p>Returns true if a backup was created.
     */
    public static boolean backup(Path path)
            throws IOException {

        if (!Files.exists(path)) {
            return false;
        }

        if (!isGenerated(path)) {
            return false;
        }

        String timestamp =
                LocalDateTime.now().format(TIMESTAMP);

        String fileName =
                path.getFileName().toString();

        Path backupPath =
                path.getParent().resolve(
                        fileName + "." + timestamp + ".old"
                );

        Files.move(path, backupPath);

        return true;
    }

    /**
     * Backup a file if it exists and is generated.
     * Returns true if backup was created or file
     * doesn't exist.
     */
    public static boolean backupIfNeeded(Path path)
            throws IOException {

        if (!Files.exists(path)) {
            return true;
        }

        return backup(path);
    }

    /**
     * Write content to a file, backing up first
     * if it is a generated file.
     *
     * <p>If the file exists and is NOT generated,
     * this is a no-op (returns false).
     *
     * @return true if the file was written
     */
    public static boolean writeWithBackup(
            Path path,
            String content,
            boolean backupEnabled)
            throws IOException {

        if (Files.exists(path)) {

            if (!isGenerated(path)) {
                return false;
            }

            if (backupEnabled) {
                backup(path);
            }
        }

        Files.createDirectories(path.getParent());

        Files.writeString(path, content);

        return true;
    }
}
