package dev.springflow.cli.generator;

import dev.springflow.cli.config.ConfigLoader;
import dev.springflow.cli.config.SpringFlowConfig;
import dev.springflow.cli.model.FieldDefinition;
import dev.springflow.cli.model.ModelDefinition;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates the full stack from a ModelDefinition:
 *
 * <ul>
 *   <li>Java: Entity, Endpoint, Service, Repository, DTO, Mapper</li>
 *   <li>React: CRUD page, data hook</li>
 * </ul>
 */
public class FileGenerator {

    private final Path projectRoot;
    private final SpringFlowConfig config;
    private final boolean backupEnabled;
    private final boolean dryRun;

    private final List<PlannedFile> planned =
            new ArrayList<>();

    public FileGenerator(
            Path projectRoot,
            boolean backupEnabled,
            boolean dryRun) {

        this.projectRoot = projectRoot;
        this.config = ConfigLoader.load(
                projectRoot.resolve(
                        "springflow.config.json"
                )
        ).withDefaults();
        this.backupEnabled = backupEnabled;
        this.dryRun = dryRun;
    }

    /**
     * Generate the full stack for a model.
     */
    public List<PlannedFile> generate(
            ModelDefinition model)
            throws IOException {

        planned.clear();

        String packageName = detectPackage();
        String packagePath =
                packageName.replace('.', '/');

        String modelPackage =
                packagePath + "/"
                        + model.pluralVarName();

        String modelPackageName =
                packageName + "."
                        + model.pluralVarName();

        // Java files
        planJavaEntity(
                model,
                modelPackage,
                modelPackageName
        );

        planJavaEndpoint(
                model,
                modelPackage,
                modelPackageName
        );

        planJavaService(
                model,
                modelPackage,
                modelPackageName
        );

        planJavaRepository(
                model,
                modelPackage,
                modelPackageName
        );

        planJavaDto(
                model,
                modelPackage,
                modelPackageName
        );

        planJavaMapper(
                model,
                modelPackage,
                modelPackageName
        );

        // React files
        planReactPage(model);

        planReactHook(model);

        // Execute
        if (!dryRun) {
            execute();
        }

        return planned;
    }

    // ================================================================
    // JAVA: ENTITY
    // ================================================================

    private void planJavaEntity(
            ModelDefinition model,
            String modelPackage,
            String modelPackageName)
            throws IOException {

        StringBuilder sb =
                new StringBuilder();

        sb.append("package ")
                .append(modelPackageName)
                .append(";\n\n");

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("public class ")
                .append(model.getName())
                .append(" {\n\n");

        for (FieldDefinition field :
                model.getFields()) {

            sb.append("    private ")
                    .append(field.getType())
                    .append(" ")
                    .append(field.getName())
                    .append(";\n");
        }

        sb.append("\n");

        // Default constructor
        sb.append("    public ")
                .append(model.getName())
                .append("() {\n");
        sb.append("    }\n\n");

        // All-args constructor (id first, then other fields)
        List<FieldDefinition> ctorFields =
                model.getFields();

        sb.append("    public ")
                .append(model.getName())
                .append("(");

        for (int i = 0; i < ctorFields.size(); i++) {

            if (i > 0) {
                sb.append(", ");
            }

            sb.append(ctorFields.get(i).getType())
                    .append(" ")
                    .append(ctorFields.get(i).getName());
        }

        sb.append(") {\n");

        for (FieldDefinition field : ctorFields) {

            sb.append("        this.")
                    .append(field.getName())
                    .append(" = ")
                    .append(field.getName())
                    .append(";\n");
        }

        sb.append("    }\n\n");

        // Getters and setters
        for (FieldDefinition field :
                model.getFields()) {

            String cap = capitalize(field.getName());

            // Getter
            if (field.isBoolean()) {

                sb.append("    public ")
                        .append(field.getType())
                        .append(" is")
                        .append(cap)
                        .append("() {\n");

                sb.append("        return ")
                        .append(field.getName())
                        .append(";\n");

            } else {

                sb.append("    public ")
                        .append(field.getType())
                        .append(" get")
                        .append(cap)
                        .append("() {\n");

                sb.append("        return ")
                        .append(field.getName())
                        .append(";\n");
            }

            sb.append("    }\n\n");

            // Setter
            sb.append("    public void set")
                    .append(cap)
                    .append("(")
                    .append(field.getType())
                    .append(" ")
                    .append(field.getName())
                    .append(") {\n");

            sb.append("        this.")
                    .append(field.getName())
                    .append(" = ")
                    .append(field.getName())
                    .append(";\n");

            sb.append("    }\n\n");
        }

        sb.append("}\n");

        addPlanned(
                "src/main/java/"
                        + modelPackage + "/"
                        + model.getName() + ".java",
                sb.toString()
        );
    }

    // ================================================================
    // JAVA: ENDPOINT
    // ================================================================

    private void planJavaEndpoint(
            ModelDefinition model,
            String modelPackage,
            String modelPackageName)
            throws IOException {

        FieldDefinition idField = model.idField();
        String idType = idField != null
                ? idField.getType()
                : "Long";

        StringBuilder sb =
                new StringBuilder();

        sb.append("package ")
                .append(modelPackageName)
                .append(";\n\n");

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("import dev.springflow.core.annotation.Endpoint;\n");
        sb.append("import dev.springflow.core.annotation.EndpointMethod;\n\n");

        sb.append("import java.util.ArrayList;\n");
        sb.append("import java.util.List;\n");
        sb.append("import java.util.concurrent.atomic.AtomicLong;\n\n");

        sb.append("@Endpoint\n");
        sb.append("public class ")
                .append(model.endpointName())
                .append(" {\n\n");

        sb.append("    private final List<")
                .append(model.getName())
                .append("> ")
                .append(model.pluralVarName())
                .append(" = new ArrayList<>();\n\n");

        sb.append("    private final AtomicLong idGenerator = new AtomicLong(1);\n\n");

        // findAll
        sb.append("    @EndpointMethod\n");
        sb.append("    public List<")
                .append(model.getName())
                .append("> findAll() {\n");
        sb.append("        return new ArrayList<>(")
                .append(model.pluralVarName())
                .append(");\n");
        sb.append("    }\n\n");

        // findById
        sb.append("    @EndpointMethod\n");
        sb.append("    public ")
                .append(model.getName())
                .append(" findById(")
                .append(idType)
                .append(" id) {\n");
        sb.append("        return ")
                .append(model.pluralVarName())
                .append(".stream()\n");
        sb.append("                .filter(item -> item.getId().equals(id))\n");
        sb.append("                .findFirst()\n");
        sb.append("                .orElse(null);\n");
        sb.append("    }\n\n");

        // create
        sb.append("    @EndpointMethod\n");
        sb.append("    public ")
                .append(model.getName())
                .append(" create(\n");

        List<FieldDefinition> createFields =
                model.createFields();

        for (int i = 0; i < createFields.size(); i++) {

            sb.append("            ");
            sb.append(createFields.get(i).getType());
            sb.append(" ");
            sb.append(createFields.get(i).getName());

            if (i < createFields.size() - 1) {
                sb.append(",");
            }

            sb.append("\n");
        }

        sb.append("    ) {\n");
        sb.append("        ")
                .append(model.getName())
                .append(" item = new ")
                .append(model.getName())
                .append("(\n");
        sb.append("                idGenerator.getAndIncrement(),\n");

        // All non-id fields in order; use defaults for
        // fields not in createFields
        List<FieldDefinition> nonIdFields =
                model.nonIdFields();

        for (int i = 0; i < nonIdFields.size(); i++) {

            FieldDefinition field = nonIdFields.get(i);

            sb.append("                ");

            if (createFields.contains(field)) {
                sb.append(field.getName());
            } else if (field.getDefaultValue() != null) {
                sb.append(field.getDefaultValue());
            } else if (field.isString()) {
                sb.append("null");
            } else if (field.isNumeric()) {
                sb.append("0");
            } else if (field.isBoolean()) {
                sb.append("false");
            } else {
                sb.append("null");
            }

            if (i < nonIdFields.size() - 1) {
                sb.append(",");
            }

            sb.append("\n");
        }

        sb.append("        );\n\n");

        sb.append("\n        ")
                .append(model.pluralVarName())
                .append(".add(item);\n");
        sb.append("        return item;\n");
        sb.append("    }\n\n");

        // update
        sb.append("    @EndpointMethod\n");
        sb.append("    public ")
                .append(model.getName())
                .append(" update(\n");

        List<FieldDefinition> updateFields =
                model.nonIdFields();

        sb.append("            ");
        sb.append(idType);
        sb.append(" id,\n");

        for (int i = 0; i < updateFields.size(); i++) {

            sb.append("            ");
            sb.append(updateFields.get(i).getType());
            sb.append(" ");
            sb.append(updateFields.get(i).getName());

            if (i < updateFields.size() - 1) {
                sb.append(",");
            }

            sb.append("\n");
        }

        sb.append("    ) {\n");
        sb.append("        ")
                .append(model.getName())
                .append(" item = findById(id);\n\n");

        sb.append("        if (item == null) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n\n");

        for (FieldDefinition field : updateFields) {

            sb.append("        item.set")
                    .append(capitalize(field.getName()))
                    .append("(")
                    .append(field.getName())
                    .append(");\n");
        }

        sb.append("\n        return item;\n");
        sb.append("    }\n\n");

        // delete
        sb.append("    @EndpointMethod\n");
        sb.append("    public boolean delete(")
                .append(idType)
                .append(" id) {\n");

        sb.append("        return ")
                .append(model.pluralVarName())
                .append(".removeIf(\n");
        sb.append("                item -> item.getId().equals(id)\n");
        sb.append("        );\n");
        sb.append("    }\n");

        sb.append("}\n");

        addPlanned(
                "src/main/java/"
                        + modelPackage + "/"
                        + model.endpointName() + ".java",
                sb.toString()
        );
    }

    // ================================================================
    // JAVA: SERVICE
    // ================================================================

    private void planJavaService(
            ModelDefinition model,
            String modelPackage,
            String modelPackageName)
            throws IOException {

        FieldDefinition idField = model.idField();
        String idType = idField != null
                ? idField.getType()
                : "Long";

        StringBuilder sb =
                new StringBuilder();

        sb.append("package ")
                .append(modelPackageName)
                .append(";\n\n");

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("import org.springframework.stereotype.Service;\n\n");

        sb.append("import java.util.ArrayList;\n");
        sb.append("import java.util.List;\n");
        sb.append("import java.util.Optional;\n\n");

        sb.append("@Service\n");
        sb.append("public class ")
                .append(model.serviceName())
                .append(" {\n\n");

        sb.append("    private final List<")
                .append(model.getName())
                .append("> store = new ArrayList<>();\n");
        sb.append("    private long nextId = 1;\n\n");

        // findAll
        sb.append("    public List<")
                .append(model.getName())
                .append("> findAll() {\n");
        sb.append("        return new ArrayList<>(store);\n");
        sb.append("    }\n\n");

        // findById
        sb.append("    public Optional<")
                .append(model.getName())
                .append("> findById(")
                .append(idType)
                .append(" id) {\n");
        sb.append("        return store.stream()\n");
        sb.append("                .filter(item -> item.getId().equals(id))\n");
        sb.append("                .findFirst();\n");
        sb.append("    }\n\n");

        // save
        sb.append("    public ")
                .append(model.getName())
                .append(" save(")
                .append(model.getName())
                .append(" item) {\n");
        sb.append("        item.setId(nextId++);\n");
        sb.append("        store.add(item);\n");
        sb.append("        return item;\n");
        sb.append("    }\n\n");

        // delete
        sb.append("    public boolean delete(")
                .append(idType)
                .append(" id) {\n");
        sb.append("        return store.removeIf(\n");
        sb.append("                item -> item.getId().equals(id)\n");
        sb.append("        );\n");
        sb.append("    }\n");

        sb.append("}\n");

        addPlanned(
                "src/main/java/"
                        + modelPackage + "/"
                        + model.serviceName() + ".java",
                sb.toString()
        );
    }

    // ================================================================
    // JAVA: REPOSITORY
    // ================================================================

    private void planJavaRepository(
            ModelDefinition model,
            String modelPackage,
            String modelPackageName)
            throws IOException {

        FieldDefinition idField = model.idField();
        String idType = idField != null
                ? idField.getType()
                : "Long";

        StringBuilder sb =
                new StringBuilder();

        sb.append("package ")
                .append(modelPackageName)
                .append(";\n\n");

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("import java.util.List;\n");
        sb.append("import java.util.Optional;\n\n");

        sb.append("/**\n");
        sb.append(" * Repository interface for ")
                .append(model.getName())
                .append(".\n");
        sb.append(" *\n");
        sb.append(" * Extend Spring Data JPA:\n");
        sb.append(" *   public interface ")
                .append(model.repositoryName())
                .append("\n");
        sb.append(" *       extends org.springframework.data.jpa.repository.JpaRepository<")
                .append(model.getName())
                .append(", ")
                .append(idType)
                .append("> {}\n");
        sb.append(" */\n");

        sb.append("public interface ")
                .append(model.repositoryName())
                .append(" {\n\n");

        sb.append("    List<")
                .append(model.getName())
                .append("> findAll();\n\n");

        sb.append("    Optional<")
                .append(model.getName())
                .append("> findById(")
                .append(idType)
                .append(" id);\n\n");

        sb.append("    ")
                .append(model.getName())
                .append(" save(")
                .append(model.getName())
                .append(" entity);\n\n");

        sb.append("    void deleteById(")
                .append(idType)
                .append(" id);\n\n");

        sb.append("    long count();\n");

        sb.append("}\n");

        addPlanned(
                "src/main/java/"
                        + modelPackage + "/"
                        + model.repositoryName() + ".java",
                sb.toString()
        );
    }

    // ================================================================
    // JAVA: DTO
    // ================================================================

    private void planJavaDto(
            ModelDefinition model,
            String modelPackage,
            String modelPackageName)
            throws IOException {

        StringBuilder sb =
                new StringBuilder();

        sb.append("package ")
                .append(modelPackageName)
                .append(";\n\n");

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("public class ")
                .append(model.dtoName())
                .append(" {\n\n");

        for (FieldDefinition field :
                model.nonIdFields()) {

            sb.append("    private ")
                    .append(field.getType())
                    .append(" ")
                    .append(field.getName())
                    .append(";\n");
        }

        sb.append("\n");

        // Default constructor
        sb.append("    public ")
                .append(model.dtoName())
                .append("() {\n");
        sb.append("    }\n\n");

        // Getters and setters
        for (FieldDefinition field :
                model.nonIdFields()) {

            String cap = capitalize(field.getName());

            if (field.isBoolean()) {

                sb.append("    public ")
                        .append(field.getType())
                        .append(" is")
                        .append(cap)
                        .append("() {\n");

            } else {

                sb.append("    public ")
                        .append(field.getType())
                        .append(" get")
                        .append(cap)
                        .append("() {\n");
            }

            sb.append("        return ")
                    .append(field.getName())
                    .append(";\n");
            sb.append("    }\n\n");

            sb.append("    public void set")
                    .append(cap)
                    .append("(")
                    .append(field.getType())
                    .append(" ")
                    .append(field.getName())
                    .append(") {\n");

            sb.append("        this.")
                    .append(field.getName())
                    .append(" = ")
                    .append(field.getName())
                    .append(";\n");

            sb.append("    }\n\n");
        }

        sb.append("}\n");

        addPlanned(
                "src/main/java/"
                        + modelPackage + "/"
                        + model.dtoName() + ".java",
                sb.toString()
        );
    }

    // ================================================================
    // JAVA: MAPPER
    // ================================================================

    private void planJavaMapper(
            ModelDefinition model,
            String modelPackage,
            String modelPackageName)
            throws IOException {

        StringBuilder sb =
                new StringBuilder();

        sb.append("package ")
                .append(modelPackageName)
                .append(";\n\n");

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("import org.springframework.stereotype.Component;\n\n");

        sb.append("@Component\n");
        sb.append("public class ")
                .append(model.mapperName())
                .append(" {\n\n");

        // toDto
        sb.append("    public ")
                .append(model.dtoName())
                .append(" toDto(")
                .append(model.getName())
                .append(" entity) {\n\n");

        sb.append("        ")
                .append(model.dtoName())
                .append(" dto = new ")
                .append(model.dtoName())
                .append("();\n\n");

        for (FieldDefinition field :
                model.nonIdFields()) {

            sb.append("        dto.set")
                    .append(capitalize(field.getName()))
                    .append("(entity.get");

            if (field.isBoolean()) {
                sb.append(capitalize(field.getName()));
            } else {
                sb.append(capitalize(field.getName()));
            }

            sb.append("());\n");
        }

        sb.append("\n        return dto;\n");
        sb.append("    }\n\n");

        // toEntity
        sb.append("    public ")
                .append(model.getName())
                .append(" toEntity(")
                .append(model.dtoName())
                .append(" dto) {\n\n");

        sb.append("        ")
                .append(model.getName())
                .append(" entity = new ")
                .append(model.getName())
                .append("();\n\n");

        for (FieldDefinition field :
                model.nonIdFields()) {

            sb.append("        entity.set")
                    .append(capitalize(field.getName()))
                    .append("(dto.get")
                    .append(capitalize(field.getName()))
                    .append("());\n");
        }

        sb.append("\n        return entity;\n");
        sb.append("    }\n");

        sb.append("}\n");

        addPlanned(
                "src/main/java/"
                        + modelPackage + "/"
                        + model.mapperName() + ".java",
                sb.toString()
        );
    }

    // ================================================================
    // REACT: CRUD PAGE
    // ================================================================

    private void planReactHook(
            ModelDefinition model)
            throws IOException {

        String hookName =
                "use" + model.pluralName();

        String varName = model.varName();
        String pluralVar = model.pluralVarName();
        String typeName = model.typescriptName();
        String pluralType = model.pluralName();
        String endpointName = model.endpointName();

        StringBuilder sb =
                new StringBuilder();

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("import { useState, useEffect }"
                + " from \"react\";\n");
        sb.append("import { ")
                .append(endpointName)
                .append(" } from \"../api\";\n");
        sb.append("import type { ")
                .append(typeName)
                .append(" } from \"../api\";\n\n");

        sb.append("export function ").append(hookName).append("() {\n\n");

        sb.append("    const [")
                .append(pluralVar)
                .append(", set")
                .append(pluralType)
                .append("] = useState<")
                .append(typeName)
                .append("[]>([]);\n\n");

        sb.append("    const [loading, setLoading]"
                + " = useState(true);\n");
        sb.append("    const [error, setError]"
                + " = useState<string | null>(null);\n\n");

        // load
        sb.append("    const load = async () => {\n");
        sb.append("        try {\n");
        sb.append("            setLoading(true);\n");
        sb.append("            const data = await ")
                .append(endpointName)
                .append(".findAll();\n");
        sb.append("            set")
                .append(pluralType)
                .append("(data);\n");
        sb.append("        } catch (err) {\n");
        sb.append("            setError(");
        sb.append("err instanceof Error ? err.message : \"Failed to load\"\n");
        sb.append("            );\n");
        sb.append("        } finally {\n");
        sb.append("            setLoading(false);\n");
        sb.append("        }\n");
        sb.append("    };\n\n");

        // create
        sb.append("    const create = async (");

        List<FieldDefinition> createFields =
                model.createFields();

        for (int i = 0; i < createFields.size(); i++) {

            if (i > 0) {
                sb.append(", ");
            }

            sb.append(createFields.get(i).getName())
                    .append(": ")
                    .append(createFields.get(i).typescriptType());
        }

        sb.append("): Promise<")
                .append(typeName)
                .append("> => {\n");

        sb.append("        const result = await ")
                .append(endpointName)
                .append(".create(");

        for (int i = 0; i < createFields.size(); i++) {

            if (i > 0) {
                sb.append(", ");
            }

            sb.append(createFields.get(i).getName());
        }

        sb.append(");\n");
        sb.append("        set")
                .append(pluralType)
                .append("(prev => [...prev, result]);\n");
        sb.append("        return result;\n");
        sb.append("    };\n\n");

        // update
        sb.append("    const update = async (");

        FieldDefinition idField = model.idField();
        String idTsType = idField != null
                ? idField.typescriptType()
                : "number";

        sb.append("id: ").append(idTsType);

        for (FieldDefinition field : model.nonIdFields()) {
            sb.append(", ")
                    .append(field.getName())
                    .append(": ")
                    .append(field.typescriptType());
        }

        sb.append("): Promise<")
                .append(typeName)
                .append("> => {\n");

        sb.append("        const result = await ")
                .append(endpointName)
                .append(".update(id");

        for (FieldDefinition field :
                model.nonIdFields()) {
            sb.append(", ").append(field.getName());
        }

        sb.append(");\n");

        sb.append("        set")
                .append(pluralType)
                .append("(prev =>\n");

        sb.append("            prev.map(item =>\n");

        sb.append("                item.id === id ? result : item\n");

        sb.append("            )\n");
        sb.append("        );\n");

        sb.append("        return result;\n");
        sb.append("    };\n\n");

        // remove
        sb.append("    const remove = async (id: ")
                .append(idTsType)
                .append(") => {\n");

        sb.append("        await ")
                .append(endpointName)
                .append(".delete(id);\n");

        sb.append("        set")
                .append(pluralType)
                .append("(prev =>\n");

        sb.append("            prev.filter(item => item.id !== id)\n");

        sb.append("        );\n");
        sb.append("    };\n\n");

        // useEffect
        sb.append("    useEffect(() => {\n");
        sb.append("        load();\n");
        sb.append("    }, []);\n\n");

        // return
        sb.append("    return {\n");

        sb.append("            ")
                .append(pluralVar)
                .append(",\n");

        sb.append("            loading,\n");
        sb.append("            error,\n");
        sb.append("            create,\n");
        sb.append("            update,\n");
        sb.append("            remove,\n");
        sb.append("            reload: load,\n");

        sb.append("    };\n");
        sb.append("}\n");

        addPlanned(
                "frontend/src/hooks/"
                        + hookName + ".ts",
                sb.toString()
        );
    }

    private void planReactPage(
            ModelDefinition model)
            throws IOException {

        String typeName = model.typescriptName();
        String pluralType = model.pluralName();
        String hookName =
                "use" + model.pluralName();
        String varName = model.varName();
        String pluralVar = model.pluralVarName();
        String pageName = model.getName() + "Page";

        StringBuilder sb =
                new StringBuilder();

        sb.append("/* Generated by SpringFlow. "
                + "DO NOT EDIT. */\n\n");

        sb.append("import { useState }"
                + " from \"react\";\n");
        sb.append("import { ConfirmDialog }"
                + " from \"../components/ConfirmDialog\";\n");
        sb.append("import { Toast }"
                + " from \"../components/Toast\";\n");
        sb.append("import { SearchInput }"
                + " from \"../components/SearchInput\";\n");
        sb.append("import { StatusBadge }"
                + " from \"../components/StatusBadge\";\n");
        sb.append("import { ")
                .append(hookName)
                .append(" } from \"../hooks/")
                .append(hookName)
                .append("\";\n");
        sb.append("import type { ")
                .append(typeName)
                .append(" } from \"../api\";\n\n");

        sb.append("export default function ")
                .append(pageName)
                .append("() {\n\n");

        sb.append("    const { ")
                .append(pluralVar)
                .append(", loading, error, create, update, remove, reload } = ")
                .append(hookName)
                .append("();\n\n");

        sb.append("    const [search, setSearch]"
                + " = useState(\"\");\n");

        sb.append("    const [showForm, setShowForm]"
                + " = useState(false);\n");

        sb.append("    const [editing, setEditing]"
                + " = useState<")
                .append(typeName)
                .append(" | null>(null);\n\n");

        List<FieldDefinition> createFields =
                model.createFields();

        sb.append("    const [showDelete, setShowDelete]"
                + " = useState(false);\n");

        sb.append("    const [deleteTarget, setDeleteTarget]"
                + " = useState<")
                .append(typeName)
                .append(" | null>(null);\n\n");

        sb.append("    const [toast, setToast]"
                + " = useState<{ message: string; type: \"success\" | \"error\" } | null>(null);\n\n");

        // Filter
        sb.append("    const filtered = ")
                .append(pluralVar)
                .append(".filter(item =>\n");

        sb.append("        JSON.stringify(item)\n");
        sb.append("            .toLowerCase()\n");
        sb.append("            .includes(search.toLowerCase())\n");
        sb.append("    );\n\n");

        // showToast helper
        sb.append("    const showToast = (message: string, type: \"success\" | \"error\" = \"success\") => {\n");
        sb.append("        setToast({ message, type });\n");
        sb.append("        setTimeout(() => setToast(null), 3000);\n");
        sb.append("    };\n\n");

        // openCreate
        sb.append("    const openCreate = () => {\n");
        sb.append("        setEditing(null);\n");
        sb.append("        setShowForm(true);\n");
        sb.append("    };\n\n");

        // openEdit
        sb.append("    const openEdit = (item: ")
                .append(typeName)
                .append(") => {\n");
        sb.append("        setEditing(item);\n");
        sb.append("        setShowForm(true);\n");
        sb.append("    };\n\n");

        // handleSave
        sb.append("    const handleSave = async (data: Record<string, unknown>) => {\n");
        sb.append("        try {\n");

        sb.append("            if (editing) {\n");

        sb.append("                await update(");

        // id param
        sb.append("editing.id as number");

        // other params
        for (FieldDefinition field :
                model.nonIdFields()) {

            sb.append(", data[\"")
                    .append(field.getName())
                    .append("\"] as ")
                    .append(field.typescriptType());
        }

        sb.append(");\n");
        sb.append("                showToast(\"")
                .append(typeName)
                .append(" updated\");\n");

        sb.append("            } else {\n");

        sb.append("                await create(");

        for (int i = 0; i < createFields.size(); i++) {

            if (i > 0) {
                sb.append(", ");
            }

            sb.append("data[\"")
                    .append(createFields.get(i).getName())
                    .append("\"] as ")
                    .append(createFields.get(i).typescriptType());
        }

        sb.append(");\n");
        sb.append("                showToast(\"")
                .append(typeName)
                .append(" created\");\n");

        sb.append("            }\n\n");

        sb.append("            setShowForm(false);\n");
        sb.append("            setEditing(null);\n");

        sb.append("        } catch (err) {\n");
        sb.append("            showToast(\n");
        sb.append("                err instanceof Error ? err.message : \"Operation failed\",\n");
        sb.append("                \"error\"\n");
        sb.append("            );\n");
        sb.append("        }\n");
        sb.append("    };\n\n");

        // handleDelete
        sb.append("    const handleDelete = async () => {\n");
        sb.append("        if (!deleteTarget) return;\n");
        sb.append("        try {\n");
        sb.append("            await remove(deleteTarget.id as number);\n");
        sb.append("            setShowDelete(false);\n");
        sb.append("            setDeleteTarget(null);\n");
        sb.append("            showToast(\"")
                .append(typeName)
                .append(" deleted\");\n");
        sb.append("        } catch (err) {\n");
        sb.append("            showToast(\n");
        sb.append("                err instanceof Error ? err.message : \"Delete failed\",\n");
        sb.append("                \"error\"\n");
        sb.append("            );\n");
        sb.append("        }\n");
        sb.append("    };\n\n");

        // JSX
        sb.append("    if (loading) {\n");
        sb.append("        return <div className=\"p-8 text-slate-500\">Loading...</div>;\n");
        sb.append("    }\n\n");

        sb.append("    if (error) {\n");
        sb.append("        return <div className=\"p-8 text-red-500\">{error}</div>;\n");
        sb.append("    }\n\n");

        sb.append("    return (\n");
        sb.append("        <div className=\"mx-auto max-w-5xl p-8\">\n\n");

        // Header
        sb.append("            <div className=\"mb-6 flex items-center justify-between\">\n");
        sb.append("                <h1 className=\"text-2xl font-bold text-slate-900\">");
        sb.append(model.pluralName());
        sb.append("</h1>\n\n");

        sb.append("                <button\n");
        sb.append("                    onClick={openCreate}\n");
        sb.append("                    className=\"rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700\"\n");
        sb.append("                >\n");
        sb.append("                    + New ");
        sb.append(typeName);
        sb.append("\n");
        sb.append("                </button>\n");
        sb.append("            </div>\n\n");

        // Search
        sb.append("            <SearchInput\n");
        sb.append("                value={search}\n");
        sb.append("                onChange={setSearch}\n");
        sb.append("                placeholder=\"Search ");
        sb.append(model.pluralVarName());
        sb.append("...\"\n");
        sb.append("            />\n\n");

        // Table
        sb.append("            <div className=\"mt-4 overflow-hidden rounded-xl border bg-white shadow\">\n");
        sb.append("                <table className=\"w-full text-left text-sm\">\n\n");

        // Thead
        sb.append("                    <thead className=\"border-b bg-slate-50 text-xs font-medium uppercase text-slate-500\">\n");
        sb.append("                        <tr>\n");

        for (FieldDefinition field :
                model.nonIdFields()) {

            sb.append("                            <th className=\"px-4 py-3\">");
            sb.append(field.getLabel());
            sb.append("</th>\n");
        }

        sb.append("                            <th className=\"px-4 py-3 text-right\">Actions</th>\n");
        sb.append("                        </tr>\n");
        sb.append("                    </thead>\n\n");

        // Tbody
        sb.append("                    <tbody className=\"divide-y\">\n");

        sb.append("                        {filtered.length === 0 && (\n");
        sb.append("                            <tr>\n");

        sb.append("                                <td colSpan={");
        sb.append(model.nonIdFields().size() + 1);
        sb.append("} className=\"px-4 py-8 text-center text-slate-400\">\n");
        sb.append("                                    No ");
        sb.append(model.pluralVarName());
        sb.append(" found\n");
        sb.append("                                </td>\n");
        sb.append("                            </tr>\n");
        sb.append("                        )}\n\n");

        sb.append("                        {filtered.map(item => (\n");
        sb.append("                            <tr key={item.id} className=\"hover:bg-slate-50\">\n");

        for (FieldDefinition field :
                model.nonIdFields()) {

            sb.append("                                <td className=\"px-4 py-3\">");

            if (field.isBoolean()) {

                sb.append("<StatusBadge active={item.")
                        .append(field.getName())
                        .append("} />");

            } else {

                sb.append("{item.")
                        .append(field.getName())
                        .append("}");
            }

            sb.append("</td>\n");
        }

        sb.append("                                <td className=\"flex justify-end gap-2 px-4 py-3\">\n");

        sb.append("                                    <button\n");
        sb.append("                                        onClick={() => openEdit(item)}\n");
        sb.append("                                        className=\"rounded border px-3 py-1 text-xs font-medium text-slate-600 hover:bg-slate-100\"\n");
        sb.append("                                    >\n");
        sb.append("                                        Edit\n");
        sb.append("                                    </button>\n\n");

        sb.append("                                    <button\n");
        sb.append("                                        onClick={() => {\n");
        sb.append("                                            setDeleteTarget(item);\n");
        sb.append("                                            setShowDelete(true);\n");
        sb.append("                                        }}\n");
        sb.append("                                        className=\"rounded border border-red-200 px-3 py-1 text-xs font-medium text-red-600 hover:bg-red-50\"\n");
        sb.append("                                    >\n");
        sb.append("                                        Delete\n");
        sb.append("                                    </button>\n");

        sb.append("                                </td>\n");
        sb.append("                            </tr>\n");
        sb.append("                        ))}\n");

        sb.append("                    </tbody>\n");
        sb.append("                </table>\n");
        sb.append("            </div>\n\n");

        // Form modal
        sb.append("            {showForm && (\n");
        sb.append("                <dialog open className=\"rounded-xl border bg-white p-6 shadow-xl\">\n");
        sb.append("                    <h2 className=\"mb-4 text-lg font-semibold\">\n");
        sb.append("                        {editing ? \"Edit ");
        sb.append(typeName);
        sb.append("\" : \"New ");
        sb.append(typeName);
        sb.append("\"\n");
        sb.append("                    </h2>\n\n");

        sb.append("                    <form\n");
        sb.append("                        onSubmit={(e) => {\n");
        sb.append("                            e.preventDefault();\n");
        sb.append("                            const formData = new FormData(e.currentTarget);\n");
        sb.append("                            const data: Record<string, unknown> = {};\n");

        for (FieldDefinition field :
                model.createFields()) {

            if (field.isNumeric()) {

                sb.append("                            data[\"")
                        .append(field.getName())
                        .append("\"] = Number(formData.get(\"")
                        .append(field.getName())
                        .append("\"));\n");

            } else if (field.isBoolean()) {

                sb.append("                            data[\"")
                        .append(field.getName())
                        .append("\"] = formData.get(\"")
                        .append(field.getName())
                        .append("\") === \"on\";\n");

            } else {

                sb.append("                            data[\"")
                        .append(field.getName())
                        .append("\"] = String(formData.get(\"")
                        .append(field.getName())
                        .append("\"));\n");
            }
        }

        sb.append("\n                            handleSave(data);\n");
        sb.append("                        }}\n");
        sb.append("                        className=\"space-y-4\"\n");
        sb.append("                    >\n");

        for (FieldDefinition field :
                model.createFields()) {

            sb.append("                        <div>\n");
            sb.append("                            <label className=\"mb-1 block text-sm font-medium text-slate-700\">");
            sb.append(field.getLabel());
            sb.append("</label>\n");

            if (field.isBoolean()) {

                sb.append("                            <input\n");
                sb.append("                                type=\"checkbox\"\n");
                sb.append("                                name=\"")
                        .append(field.getName())
                        .append("\"\n");
                sb.append("                                defaultChecked={")
                        .append(field.getDefaultValue() != null
                                ? field.getDefaultValue()
                                : "false")
                        .append("}\n");
                sb.append("                                className=\"h-4 w-4 rounded border-slate-300\"\n");
                sb.append("                            />\n");

            } else {

                sb.append("                            <input\n");
                sb.append("                                type=\"")
                        .append(field.isNumeric() ? "number" : "text")
                        .append("\"\n");
                sb.append("                                name=\"")
                        .append(field.getName())
                        .append("\"\n");
                sb.append("                                defaultValue={editing?.")
                        .append(field.getName())
                        .append(" ?? \"\"}\n");

                if (field.getMax() != null) {
                    sb.append("                                maxLength={")
                            .append(field.getMax())
                            .append("}\n");
                }

                sb.append("                                required={")
                        .append(field.isRequired())
                        .append("}\n");
                sb.append("                                className=\"w-full rounded-lg border border-slate-300 px-3 py-2 text-sm\"\n");
                sb.append("                            />\n");
            }

            sb.append("                        </div>\n\n");
        }

        sb.append("                        <div className=\"flex justify-end gap-3 pt-2\">\n");

        sb.append("                            <button\n");
        sb.append("                                type=\"button\"\n");
        sb.append("                                onClick={() => { setShowForm(false); setEditing(null); }}\n");
        sb.append("                                className=\"rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50\"\n");
        sb.append("                            >\n");
        sb.append("                                Cancel\n");
        sb.append("                            </button>\n\n");

        sb.append("                            <button\n");
        sb.append("                                type=\"submit\"\n");
        sb.append("                                className=\"rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700\"\n");
        sb.append("                            >\n");
        sb.append("                                {editing ? \"Save\" : \"Create\"}\n");
        sb.append("                            </button>\n");

        sb.append("                        </div>\n");
        sb.append("                    </form>\n");
        sb.append("                </dialog>\n");
        sb.append("            )}\n\n");

        // Delete confirm
        sb.append("            <ConfirmDialog\n");
        sb.append("                open={showDelete}\n");
        sb.append("                title=\"Delete ");
        sb.append(typeName);
        sb.append("\"\n");

        sb.append("                message={`Are you sure you want to delete this ");
        sb.append(varName);
        sb.append("?`}\n");

        sb.append("                confirmLabel=\"Delete\"\n");
        sb.append("                destructive\n");
        sb.append("                onConfirm={handleDelete}\n");
        sb.append("                onCancel={() => { setShowDelete(false); setDeleteTarget(null); }}\n");
        sb.append("            />\n\n");

        // Toast
        sb.append("            {toast && (\n");
        sb.append("                <Toast message={toast.message} type={toast.type} />\n");
        sb.append("            )}\n");

        sb.append("        </div>\n");
        sb.append("    );\n");
        sb.append("}\n");

        addPlanned(
                "frontend/src/pages/"
                        + pageName + ".tsx",
                sb.toString()
        );
    }

    // ================================================================
    // HELPERS
    // ================================================================

    private void addPlanned(
            String relativePath,
            String content) {

        planned.add(new PlannedFile(
                relativePath,
                content
        ));
    }

    private void execute() throws IOException {

        for (PlannedFile file : planned) {

            Path path =
                    projectRoot.resolve(file.relativePath);

            boolean written =
                    BackupManager.writeWithBackup(
                            path,
                            file.content,
                            backupEnabled
                    );

            if (written) {

                System.out.println(
                        "  + " + file.relativePath
                );

            } else {

                System.out.println(
                        "  ~ " + file.relativePath
                        + " (skipped, not generated)"
                );
            }
        }
    }

    /**
     * Detect the Java package name from the existing
     * Application.java file.
     */
    private String detectPackage() {

        Path srcDir =
                projectRoot.resolve("src/main/java");

        if (!Files.isDirectory(srcDir)) {
            return "com.example.app";
        }

        try {

            return Files.walk(srcDir)
                    .filter(p -> p.getFileName()
                            .toString()
                            .equals("Application.java"))
                    .findFirst()
                    .map(p -> {
                        try {
                            String content =
                                    Files.readString(p);

                            int pkgStart =
                                    content.indexOf("package ");

                            if (pkgStart < 0) {
                                return "com.example.app";
                            }

                            int pkgEnd =
                                    content.indexOf(
                                            ';',
                                            pkgStart
                                    );

                            if (pkgEnd < 0) {
                                return "com.example.app";
                            }

                            return content
                                    .substring(
                                            pkgStart + 8,
                                            pkgEnd
                                    )
                                    .trim();

                        } catch (IOException e) {
                            return "com.example.app";
                        }
                    })
                    .orElse("com.example.app");

        } catch (IOException e) {
            return "com.example.app";
        }
    }

    private static String capitalize(String name) {

        if (name == null || name.isEmpty()) {
            return name;
        }

        return Character.toUpperCase(name.charAt(0))
                + name.substring(1);
    }

    /**
     * A file planned for generation.
     */
    public record PlannedFile(
            String relativePath,
            String content
    ) {
    }
}
