package dev.springflow.cli.commands;

import dev.springflow.cli.config.ConfigLoader;
import dev.springflow.cli.config.SpringFlowConfig;
import dev.springflow.cli.util.Processes;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class GenerateCommand implements Command {

    public static final String GENERATED_SOURCE =
            "springflow/generated";

    private static final String FALLBACK_CLIENT =
            """
            /* Generated by SpringFlow. DO NOT EDIT. */

            export class SpringFlowClient {

                static async get<T>(
                    url: string,
                    params?: Record<string, unknown>
                ): Promise<T> {

                    const searchParams =
                        new URLSearchParams();

                    if (params) {
                        for (const [key, value] of Object.entries(params)) {
                            searchParams.set(
                                key,
                                String(value)
                            );
                        }
                    }

                    const query =
                        searchParams.toString();

                    const finalUrl =
                        url +
                        (query ? `?${query}` : "");

                    const response =
                        await fetch(finalUrl);

                    if (!response.ok) {

                        throw new Error(
                            `SpringFlow request failed: ${response.status} ${response.statusText}`
                        );
                    }

                    return await response.json();
                }

                static async post<T>(
                    url: string,
                    body?: Record<string, unknown>
                ): Promise<T> {

                    const response =
                        await fetch(url, {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                            },
                            body: body
                                ? JSON.stringify(body)
                                : undefined,
                        });

                    if (!response.ok) {

                        throw new Error(
                            `SpringFlow request failed: ${response.status} ${response.statusText}`
                        );
                    }

                    return await response.json();
                }
            }
            """;

    @Override
    public void run(String[] args) {

        System.out.println();
        System.out.println("SpringFlow Generate");
        System.out.println();

        runGeneration();
    }

    /**
     * Shared by generate, dev and build:
     *
     * validate project -> compile (annotation processor) ->
     * synchronize target/classes/springflow/generated -> frontend/src/api ->
     * write index.ts
     */
    public static void runGeneration() {

        validateProject();
        Processes.requireMaven();

        System.out.println("✓ Scanning endpoints");

        int compileExit =
                Processes.run(
                        Path.of("."),
                        Processes.mavenCommand(),
                        "clean",
                        "compile"
                );

        if (compileExit != 0) {
            throw new CliException(
                    "Maven compile failed with exit code "
                            + compileExit
            );
        }

        SpringFlowConfig config =
                ConfigLoader.load();

        Path apiDirectory =
                Path.of(config.apiDirectory())
                        .toAbsolutePath()
                        .normalize();

        Path generatedSource =
                Path.of("target", "classes", GENERATED_SOURCE);

        List<Path> generatedFiles =
                generatedFiles(generatedSource);

        Map<Path, Path> newFiles =
                new LinkedHashMap<>();

        List<String> modules =
                new ArrayList<>();

        try {

            if (generatedFiles.isEmpty()) {

                // No @Endpoint classes yet. Still produce a usable
                // API directory with the shared SpringFlowClient.
                Files.createDirectories(apiDirectory);

                Path client =
                        apiDirectory.resolve("SpringFlowClient.ts");

                Files.writeString(
                        client,
                        FALLBACK_CLIENT,
                        StandardCharsets.UTF_8
                );

                newFiles.put(
                        Path.of("SpringFlowClient.ts"),
                        client
                );

                modules.add("SpringFlowClient");

                System.out.println(
                        "✓ No endpoints found, generated shared SpringFlowClient"
                );

            } else {

                Files.createDirectories(apiDirectory);

                for (Path file : generatedFiles) {

                    Path relative =
                            generatedSource.relativize(file);

                    newFiles.put(relative, file);
                }

                for (Path file : generatedFiles) {

                    Path relative =
                            generatedSource.relativize(file);

                    modules.add(
                            toModuleName(relative)
                    );
                }

                for (Map.Entry<Path, Path> entry : newFiles.entrySet()) {

                    Path destination =
                            apiDirectory.resolve(entry.getKey());

                    Files.createDirectories(
                            destination.getParent()
                    );

                    Files.copy(
                            entry.getValue(),
                            destination,
                            StandardCopyOption.REPLACE_EXISTING
                    );
                }
            }

            // Remove stale generated .ts files so deleted Java
            // endpoints disappear from the frontend API.
            Files.walk(apiDirectory)
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName()
                            .toString()
                            .endsWith(".ts"))
                    .forEach(path -> {
                        Path relative = apiDirectory.relativize(path);
                        if (!newFiles.containsKey(relative)) {
                            try {
                                Files.deleteIfExists(path);
                            } catch (IOException ignored) {
                                // best effort
                            }
                        }
                    });

        } catch (IOException e) {

            throw new CliException(
                    "Failed to synchronize frontend API: "
                            + e.getMessage()
            );
        }

        writeIndex(
                apiDirectory,
                modules
        );

        System.out.println("✓ Generating TypeScript");
        System.out.println("✓ Updating " + config.apiDirectory());
        System.out.println("✓ Synchronized " + modules.size() + " generated files");
        System.out.println("✓ Generated index.ts");
    }

    private static void validateProject() {

        boolean hasPom =
                Files.exists(Path.of("pom.xml"));

        boolean hasConfig =
                Files.exists(Path.of("springflow.config.json"));

        if (!hasPom && !hasConfig) {

            throw new CliException(
                    "No SpringFlow project found.\n\n"
                            + "Expected:\n"
                            + "  pom.xml\n"
                            + "  or\n"
                            + "  springflow.config.json\n\n"
                            + "Run:\n"
                            + "  springflow create my-app"
            );
        }
    }

    private static List<Path> generatedFiles(
            Path generatedSource) {

        List<Path> files =
                new ArrayList<>();

        if (!Files.isDirectory(generatedSource)) {
            return files;
        }

        try {

            Files.walk(generatedSource)
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName()
                            .toString()
                            .endsWith(".ts"))
                    .sorted()
                    .forEach(files::add);

        } catch (IOException e) {

            throw new CliException(
                    "Failed to scan generated files: "
                            + e.getMessage()
            );
        }

        return files;
    }

    private static String toModuleName(
            Path relative) {

        String path = relative
                .toString()
                .replace('\\', '/');

        return path.substring(
                0,
                path.length() - 3
        );
    }

    private static void writeIndex(
            Path apiDirectory,
            List<String> modules) {

        StringBuilder output =
                new StringBuilder();

        output.append(
                "/* Generated by SpringFlow. DO NOT EDIT. */\n\n"
        );

        for (String module : modules) {
            output.append("export * from \"./")
                    .append(module)
                    .append("\";\n");
        }

        try {

            Files.writeString(
                    apiDirectory.resolve("index.ts"),
                    output.toString(),
                    StandardCharsets.UTF_8
            );

        } catch (IOException e) {

            throw new CliException(
                    "Failed to write index.ts: "
                            + e.getMessage()
            );
        }
    }
}
